services:
  vscsync:
    image: vscsync:latest
    build:
      context: ./
      dockerfile: ./_resources/sync.Dockerfile
    volumes:
      - ./artifacts/:/artifacts/ # change for artifacts location
    environment:
      - SYNCARGS=--sync
      # Enable to sync all extensions
      #- SYNCARGS=--syncall
      # Enable a logfile
      #- SYNCARGS=--sync --logfile /logs/sync.log
  vscgallery:
    image: vscgallery:latest
    build:
      context: ./
      dockerfile: ./_resources/server.Dockerfile
    volumes:
      - ./artifacts/:/artifacts/ # change for artifacts location
      # Enable to store logfiles in its own folder
      # ./logs/:/logs/
    ports:
      - 9000:9000
    environment:
      - BIND=0.0.0.0:9000
